// Code generated by the dharitri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]
#![feature(lang_items)]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    dharitri_sc_wrewa_swap
    (
        wrapRewa
        unwrapRewa
        getLockedRewaBalance
        getWrappedRewaTokenId
        pause
        unpause
        isPaused
    )
}

dharitri_sc_wasm_adapter::empty_callback! {}
