// Code generated by the numbat-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

numbat_wasm_node::wasm_endpoints! {
    dcdt_system_sc_mock
    (
        issue
        issueNonFungible
        issueSemiFungible
        registerMetaDCDT
        setSpecialRole
        registerAndSetAllRoles
    )
}

numbat_wasm_node::wasm_empty_callback! {}
