// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    auto_pos_creator
    (
        init => init
        upgrade => upgrade
        createLpPosFromSingleToken => create_lp_pos_from_single_token
        createLpPosFromTwoTokens => create_lp_pos_from_two_tokens
        createFarmPosFromSingleToken => create_farm_pos_from_single_token
        createFarmPosFromTwoTokens => create_farm_pos_from_two_tokens
        createMetastakingPosFromSingleToken => create_metastaking_pos_from_single_token
        createMetastakingPosFromTwoTokens => create_metastaking_pos_from_two_tokens
        createFarmStakingPosFromSingleToken => create_farm_staking_pos_from_single_token
        exitMetastakingPos => exit_metastaking_pos_endpoint
        exitFarmPos => exit_farm_pos
        exitLpPos => exit_lp_pos
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
