// Code generated by the numbat-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

numbat_wasm_node::wasm_endpoints! {
    erc721
    (
        mint
        approve
        revoke
        transfer
        totalMinted
        tokenOwner
        tokenCount
        approval
    )
}

numbat_wasm_node::wasm_empty_callback! {}
