// Code generated by the dharitri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]
#![feature(lang_items)]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    order_book_pair
    (
        createBuyOrder
        createSellOrder
        matchOrders
        cancelOrders
        cancelAllOrders
        freeOrders
        startGlobalOperation
        stopGlobalOperation
        getAddressOrderIds
        getOrderIdCounter
        getOrderById
        getFirstTokenId
        getSecondTokenId
    )
}

dharitri_sc_wasm_adapter::empty_callback! {}
