// Code generated by the numbat-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           15
// Async Callback (empty):               1
// Total number of exported functions:  17

#![no_std]

numbat_wasm_node::wasm_endpoints! {
    payable_features
    (
        echo_call_value
        payment_multiple
        payment_array_3
        payable_any_1
        payable_any_2
        payable_any_3
        payable_any_4
        payable_rewa_1
        payable_rewa_2
        payable_rewa_3
        payable_rewa_4
        payable_token_1
        payable_token_2
        payable_token_3
        payable_token_4
    )
}

numbat_wasm_node::wasm_empty_callback! {}
