// Code generated by the numbat-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            0
// Async Callback (empty):               1
// Total number of exported functions:   2

#![no_std]

numbat_wasm_node::wasm_endpoints! {
    empty
    (
    )
}

numbat_wasm_node::wasm_empty_callback! {}
