// Code generated by the dharitri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    dcdt_system_sc_mock
    (
        init => init
        issue => issue_fungible
        issueNonFungible => issue_non_fungible
        issueSemiFungible => issue_semi_fungible
        registerMetaDCDT => issue_meta_dcdt
        setSpecialRole => set_special_roles
        registerAndSetAllRoles => register_and_set_all_roles
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
