// Code generated by the numbat-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            3
// Async Callback (empty):               1
// Total number of exported functions:   5

#![no_std]

numbat_wasm_node::wasm_endpoints! {
    proxy_test_second
    (
        payMe
        payMeWithResult
        messageMe
    )
}

numbat_wasm_node::wasm_empty_callback! {}
