// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    header_verifier
    (
        init => init
        upgrade => upgrade
        registerBridgeOps => register_bridge_operations
        setDcdtSafeAddress => set_dcdt_safe_address
        removeExecutedHash => remove_executed_hash
        lockOperationHash => lock_operation_hash
        setMinValidSigners => set_min_valid_signers
        addSigners => add_signers
        removeSigners => remove_signers
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
