// Code generated by the dharitri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            4
// Async Callback:                       1
// Total number of exported functions:   6

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    fractional_nfts
    (
        init => init
        claimRoyaltiesFromMarketplace => claim_royalties_from_marketplace
        fractionalizeNFT => fractionalize_nft
        unFractionalizeNFT => unfractionalize_nft
        getFractionalToken => fractional_token
    )
}

dharitri_sc_wasm_adapter::async_callback! { fractional_nfts }
