// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback:                       1
// Total number of exported functions:  14

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    paint_harvest_sc
    (
        init => init
        upgrade => upgrade
        start_harvest => start_harvest
        claim_harvest => claim_harvest
        change_harvest_color => change_harvest_color
        stop_harvest => stop_harvest
        open_contract => open_contract
        close_contract => close_contract
        change_color_harvest_duration => change_color_harvest_duration
        issue_semi_fungible => issue_semi_fungible
        set_special_roles => set_special_roles
        create_sft => create_sft
        add_quantity => add_quantity
    )
}

dharitri_sc_wasm_adapter::async_callback! { paint_harvest_sc }
