// Code generated by the dharitri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           13
// Async Callback:                       1
// Total number of exported functions:  15

#![no_std]
#![feature(alloc_error_handler, lang_items)]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    erc1155
    (
        safeTransferFrom
        safeBatchTransferFrom
        setApprovalForAll
        createToken
        mint
        burn
        balanceOf
        balanceOfBatch
        getTokenOwner
        getTokenTypeCreator
        getTokenTypeUri
        isFungible
        isApprovedForAll
        callBack
    )
}
