// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            4
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    composable_tasks
    (
        init => init
        upgrade => upgrade
        composeTasks => compose_tasks
        setWrapRewaAddr => set_wrap_rewa_address
        setRouterAddr => set_router_address
        getPair => get_pair
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
