// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

dharitri_sc_wasm_adapter::allocator!(leaking);
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    auction_mock
    (
        init => init
        stake => stake
        unStake => unstake_endpoint
        unStakeNodes => unstake_nodes_endpoint
        unBond => unbond_endpoint
        unBondNodes => unbond_nodes_endpoint
        unStakeTokens => unstake_tokens
        unBondTokens => unbond_tokens
        claim => claim
        unJail => unjail_endpoint
        setBlsDeliberateError => set_bls_deliberate_error
        getBlsDeliberateError => get_bls_deliberate_error
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
