// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    chain_factory
    (
        init => init
        upgrade => upgrade
        deploySovereignChainConfigContract => deploy_sovereign_chain_config_contract
        blacklistSovereignChainSc => blacklist_sovereign_chain_sc
        getDeployCost => deploy_cost
        slash => slash
        distributeSlashed => distribute_slashed
        setMinValidSigners => set_min_valid_signers
        addSigners => add_signers
        removeSigners => remove_signers
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
