// Code generated by the numbat-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            2
// Async Callback:                       1
// Total number of exported functions:   4

#![no_std]

numbat_wasm_node::wasm_endpoints! {
    child
    (
        issueWrappedRewa
        getWrappedRewaTokenIdentifier
        callBack
    )
}
