// Code generated by the numbat-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

numbat_wasm_node::wasm_endpoints! {
    erc20
    (
        totalSupply
        balanceOf
        allowance
        transfer
        transferFrom
        approve
    )
}

numbat_wasm_node::wasm_empty_callback! {}
