// Code generated by the dharitri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           18
// Async Callback:                       1
// Total number of exported functions:  20

#![no_std]
#![no_main]
#![feature(alloc_error_handler, lang_items)]

// dharitri_sc_wasm_adapter::allocator!();
// dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    dns
    (
        canRegister
        register
        migrate
        resolve
        resolveFromHash
        getNameValueState
        claim
        setUpdateGasLimit
        getRegistrationCost
        getValueState
        getUpdateGasLimit
        getContractOwner
        getOwnShardId
        nameHash
        nameShard
        validateName
        version
        setFeatureFlag
        callBack
    )
}
