// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    chain_config
    (
        init => init
        upgrade => upgrade
        deployBridge => deploy_bridge
        getMinValidators => min_validators
        getMaxValidators => max_validators
        getMinStake => min_stake
        getAdditionalStakeRequired => additional_stake_required
        wasPreviouslySlashed => was_previously_slashed
        isAdmin => is_admin
        addAdmin => add_admin
        removeAdmin => remove_admin
        getAdmins => admins
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
