// Code generated by the TerraDharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            3
// Async Callback (empty):               1
// Total number of exported functions:   6

#![no_std]

dharitri_wasm_adapter::allocator!();
dharitri_wasm_adapter::panic_handler!();

dharitri_wasm_adapter::endpoints! {
    simple_dcdt_test
    (
        init => init
        upgrade => upgrade
        local_mint => local_mint
        burn => burn
        nft_create => nft_create
    )
}

dharitri_wasm_adapter::async_callback_empty! {}
