// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::external_view_init! {}

dharitri_sc_wasm_adapter::external_view_endpoints! {
    multisig_improved
    (
        getPendingActionFullInfo => get_pending_action_full_info
        getActionSignerCount => get_action_signer_count
        getActionValidSignerCount => get_action_valid_signer_count_view
        getActionSigners => get_action_signers_view
        userRole => user_role
        getAllBoardMembers => get_all_board_members
        getAllProposers => get_all_proposers
        getActionData => get_action_data
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
