// Code generated by the numbat-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           19
// Async Callback (empty):               1
// Total number of exported functions:  21

#![no_std]

numbat_wasm_node::wasm_endpoints! {
    numbat_sc_price_aggregator
    (
        addOracles
        removeOracles
        submit
        submitBatch
        latestRoundData
        latestPriceFeed
        latestPriceFeedOptional
        setSubmissionCount
        getOracles
        setPairDecimals
        getPairDecimals
        submission_count
        pause
        unpause
        isPaused
        stake
        unstake
        voteSlashMember
        slashMember
    )
}

numbat_wasm_node::wasm_empty_callback! {}
