// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    passthrough
    (
        init => init
        upgrade => upgrade
        getMultisigAddress => multisig_address
        addInteraction => add_interaction
        disableInteraction => disable_interaction
        enableInteraction => enable_interaction
        addAllowedAddresses => add_allowed_addresses
        removeAllowedAddresses => remove_allowed_addresses
        setAllowedTokenForInteraction => set_allowed_token_for_interaction
        canExecute => can_execute
        getAllowedUsersForInteraction => get_allowed_users_for_interaction
        getAllowedTokenForInteraction => get_allowed_token_for_interaction
        getInteractionStatus => get_interaction_status
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
