// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            7
// Async Callback:                       1
// Total number of exported functions:  10

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    my_token_contract
    (
        init => init
        upgrade => upgrade
        issue_nft_token_id => issue_nft_token_id
        issue_sft_token_id => issue_sft_token_id
        issue_fungible_token_id => issue_fungible_token_id
        add_roles => add_roles
        add_quantity => add_quantity
        mint_nft => mint_nft
        last_issued_token_id => last_issued_token_id
    )
}

dharitri_sc_wasm_adapter::async_callback! { my_token_contract }
