// Code generated by the numbat-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           26
// Async Callback:                       1
// Total number of exported functions:  28

#![no_std]

numbat_wasm_node::wasm_endpoints! {
    rust_testing_framework_tester
    (
        sum
        sum_sc_result
        get_caller_legacy
        get_rewa_balance
        get_dcdt_balance
        receive_rewa
        recieve_rewa_half
        receive_dcdt
        reject_payment
        receive_dcdt_half
        receive_multi_dcdt
        send_nft
        mint_dcdt
        burn_dcdt
        create_nft
        get_block_epoch
        get_block_nonce
        get_block_timestamp
        get_random_buffer_once
        get_random_buffer_twice
        call_other_contract_execute_on_dest
        call_other_contract_add_async_call
        getTotalValue
        execute_on_dest_add_value
        addValue
        panic
        callBack
    )
}
