// Code generated by the numbat-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            2
// Async Callback (empty):               1
// Total number of exported functions:   4

#![no_std]

numbat_wasm_node::wasm_endpoints! {
    order_book_factory
    (
        createPair
        getPair
    )
}

numbat_wasm_node::wasm_empty_callback! {}
