// Code generated by the dharitri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           18
// Async Callback:                       1
// Total number of exported functions:  20

#![no_std]
#![feature(lang_items)]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    local_dcdt_and_nft
    (
        issueFungibleToken
        localMint
        localBurn
        nftIssue
        nftCreate
        nftAddQuantity
        nftBurn
        transferNftViaAsyncCall
        transfer_nft_and_execute
        sftIssue
        setLocalRoles
        unsetLocalRoles
        controlChanges
        getFungibleDcdtBalance
        getNftBalance
        getCurrentNftNonce
        lastIssuedToken
        lastErrorMessage
        callBack
    )
}
