// Code generated by the dharitri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]
#![feature(alloc_error_handler, lang_items)]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::external_view_endpoints! {
    multisig
    (
        getPendingActionFullInfo
        userRole
        getAllBoardMembers
        getAllProposers
        getActionData
        getActionSigners
        getActionSignerCount
        getActionValidSignerCount
    )
}

dharitri_sc_wasm_adapter::empty_callback! {}
