// Code generated by the dharitri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           21
// Async Callback:                       1
// Total number of exported functions:  23

#![no_std]
#![feature(lang_items)]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    kitty_ownership
    (
        setGeneScienceContractAddress
        setKittyAuctionContractAddress
        claim
        totalSupply
        balanceOf
        ownerOf
        approve
        transfer
        transfer_from
        tokensOfOwner
        allowAuctioning
        approveSiringAndReturnKitty
        createGenZeroKitty
        getKittyById
        isReadyToBreed
        isPregnant
        canBreedWith
        approveSiring
        breedWith
        giveBirth
        birthFee
        callBack
    )
}
