// Code generated by the numbat-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

numbat_wasm_node::wasm_endpoints! {
    token_release
    (
        addFixedAmountGroup
        addPercentageBasedGroup
        removeGroup
        addUserGroup
        removeUser
        requestAddressChange
        approveAddressChange
        endSetupPeriod
        claimTokens
        verify_address_change
        get_claimable_tokens
        getTokenIdentifier
        getTokenTotalSupply
    )
}

numbat_wasm_node::wasm_empty_callback! {}
