// Code generated by the dharitri-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]
#![feature(lang_items)]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    vault
    (
        echo_arguments
        echo_arguments_without_storage
        echo_caller
        accept_funds
        accept_funds_echo_payment
        accept_funds_single_dcdt_transfer
        reject_funds
        retrieve_funds_with_transfer_exec
        retrieve_funds
        retrieve_multi_funds_async
        burn_and_create_retrive_async
        get_owner_address
        call_counts
    )
}

dharitri_sc_wasm_adapter::empty_callback! {}
